/*
 * libinsight, a libary to stream data in binary form to a host computer.
 *
 * Copyright (C) 2021 Julian Friedrich
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>. 
 *
 * You can file issues at https://github.com/fjulian79/libinsight/issues
 */

#ifndef INSIGHT_CONFIG_HPP_
#define INSIGHT_CONFIG_HPP_

#ifndef INSIGHT_NUMVALUES
/**
 * @brief Defines the number of values which can be added to a stream.
 */
#define INSIGHT_NUMVALUES           5
#endif

#ifndef INSIGHT_NAMEBUFFERSIZ
/**
 * @brief Defines the size of the internal buffer used to store the data names
 * given by the user.
 */
#define INSIGHT_NAMEBUFFERSIZ       32
#endif

#ifndef INSIGHT_TASKPERIOD_MS
/**
 * @brief Defines the default task period.
 */
#define INSIGHT_TASKPERIOD_MS       250
#endif

#ifndef INSIGHT_BINARYINFO_FMT

/**
 * This include at this position is related to the VERSION_XXX defintions in the
 * INSIGHT_BINARYINFO_FMT defnition below. 
 * 
 * This header is generated by https://github.com/fjulian79/libversion/. 
 * 
 * As time of writing I'm not aware of a possibility to state conditional 
 * dependencies in platformio (library.json). As consequence I have decided to 
 * state the dependency here and give the user the chance to decide if he want's
 * to have libversion in his project or not. Hence, if the depency would have 
 * been added to library.json it would be more work to get rid of it then just 
 * adding libversion to your platformio.ini file ;-)
 */
#include "version/version.h"

/**
 * @brief The default definition of the binary infos transmitted in the header.
 * 
 * This is defintion is used in a printf() call and has to provide the formatter 
 * as well as the arguments. It has to result in three csv fields sepparated by 
 * semicolons. All those fields are expected to be strings. Those fields shall 
 * provide the following content:
 * 
 * Field 0:     The Name identifying the binary, e.g. the name of the project.
 *              This name is used ont he host computer for filenames when 
 *              writing the streamed data to the disk.
 * 
 * Field 1:     Version information to be able to identify which version of the 
 *              binary has produced the data. This field is not used for 
 *              filenames.
 * 
 * Field 2:     Some kind of a timestamp related to the build of the binary.
 *              Might also be a build number or just __DATE__
 *
 * ATTENTION: DO NOT USE SEMICOLONS FOR ANY OTHER PURPOSE THEN FIELD SEPARATION!
 */
#define INSIGHT_BINARYINFO_FMT      "%s; %s; %s %s;",                   \
                                    VERSION_PROJECT, VERSION_GIT_LONG,  \
                                    VERSION_DATE, VERSION_TIME
#endif

#endif /* INSIGHT_CONFIG_HPP_ */